repos:
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v7.22.0
      hooks:
          - id: eslint
            args: ["--fix"]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.2.1
      hooks:
          - id: prettier
