# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
    # Declare a dependency on the welcome-orb
    welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
    install-lint:
        machine:
            image: ubuntu-2004:202201-02
        working_directory: ~/cdc-frontend
        steps:
            - checkout
            - run: npm install && npm run lint
    install-build:
        machine:
            image: ubuntu-2004:202201-02
        working_directory: ~/cdc-frontend
        steps:
            - checkout
            - run: npm install && npm run build
workflows:
    # Name the workflow "welcome"
    welcome:
        # Run the welcome/run job in its own container
        jobs:
            - install-lint
            - install-build
